version: "3"

services:
  stride:
    build:
      context: .
      args:
        USER: ${USER}
        UID: ${UID}
    container_name: "stride"
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: "host"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
      - "/etc/localtime:/etc/localtime"
      - "/dev/shm:/dev/shm"
      - "stride:/home/${USER}/.config/Stride"
    devices:
      - /dev/snd
volumes:
  stride:
